name: rikulo_ui
version: 0.6.3+2
description: > 
  Rikulo UI is a cross-platform framework for creating amazing 
  Web and mobile applications in Dart & HTML5.
authors:
- Tom Yeh <tomyeh@rikulo.org>
- Simon Pai <simonpai@rikulo.org>
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org/projects/ui
dependencies:
  rikulo_commons: any
  browser: any
  meta: any
