name: rikulo
version: 0.6.0
description: > 
  Rikulo is a free and open source framework for creating incredible 
  cross-platform web and native mobile applications in Dart & HTML5.
authors:
- Tom Yeh <tomyeh@rikulo.org>
- Simon Pai <simonpai@rikulo.org>
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org
