name: rikulo_ui
version: 0.6.6+2
description: > 
  A cross-platform framework for creating amazing 
  Web and native mobile applications in Dart & HTML5.
authors:
- Tom Yeh <tomyeh@rikulo.org>
- Simon Pai <simonpai@rikulo.org>
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org/projects/ui
dependencies:
  rikulo_commons: {path: ../commons}
  browser: any
  meta: any
